org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
kotlin.code.style=official

# Dokka V2 migration
org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers

# Project metadata for Maven publishing
GROUP=com.github.slavikjunior.kache
VERSION_NAME=0.1.0-SNAPSHOT

POM_DESCRIPTION=Enterprise-grade Kotlin Multiplatform caching library with L1/L2 tiers and reactive strategy pipeline
POM_URL=https://github.com/slavikjunior/Kache
POM_SCM_URL=https://github.com/slavikjunior/Kache
POM_SCM_CONNECTION=scm:git:git://github.com/slavikjunior/Kache.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/slavikjunior/Kache.git

POM_LICENCE_NAME=MIT License
POM_LICENCE_URL=https://opensource.org/licenses/MIT
POM_LICENCE_DIST=repo

POM_DEVELOPER_ID=slavikjunior
POM_DEVELOPER_NAME=Vyacheslav
