package io.github.slavikjunior.kache.store.room

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor

/**
 * Room database for Kache persistent storage.
 *
 * Contains a single table [CacheEntryEntity] for storing serialized cache entries
 * with TTL metadata.
 */
@ConstructedBy(KacheDatabaseConstructor::class)
@Database(
    entities = [CacheEntryEntity::class],
    version = 2,
    exportSchema = true
)
public abstract class KacheDatabase : RoomDatabase() {
    public abstract fun cacheEntryDao(): CacheEntryDao
}

/**
 * Platform-neutral entry point for instantiating [KacheDatabase].
 *
 * Room instantiates the generated implementation reflectively on Android and through the
 * generated `actual` object on every other target, which is why a database that lives in
 * a common source set has to be linked to this declaration via [ConstructedBy].
 *
 * The `actual` implementation is generated by the Room compiler, so this declaration has
 * no counterpart in the source tree.
 */
@Suppress("KotlinNoActualForExpect")
public expect object KacheDatabaseConstructor : RoomDatabaseConstructor<KacheDatabase> {
    override fun initialize(): KacheDatabase
}